spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-mowen-dev
---
spring: 
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-mowen-test
#必须保存为UTF-8